apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: minikube-master-service-account
          restartPolicy: Never
          containers:
          - name: cron-test-container
            image: python-helloworld:latest
            imagePullPolicy: IfNotPresent      
            envFrom:
            - secretRef:
                name: hello-secret
            - configMapRef:
                name: hello-configmap