apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: pod-container
    image: busybox
    command: 
    - /bin/sh
    - -c 
    - echo $GREETING_CONFIGMAP
    envFrom:
    - configMapRef:
        name: hello-configmap
